### ISSUE TITLE
Stale content type during syncdb

### ISSUE THREAD

**Issue by sneawo** [zlorf/django-synchro#10]
In Django 1.7 for each syncdb command I have:

```
The following content types are stale and need to be deleted:

    synchro |
```

Seems it comes from `options = SynchroSettings()` in models.py

**Comment by sneawo** [comment]
The issue in dbsettings https://github.com/zlorf/django-dbsettings/issues/7

**Comment by zlorf** [comment]
Closing it as it is issue with dependent library.
