### ISSUE TITLE
django-synchro always display no changes

### ISSUE THREAD

**Issue by weslie** [zlorf/django-synchro#11]
I am trying to use an django plugin at https://github.com/zlorf/django-synchro#skipping-fields

But it always say "No changes since last synchronization."

Here is settings snippet:

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wnitest',
    'dbsettings',
    'synchro',
    'xadmin',
    'crispy_forms',
    'debug_toolbar',
)

DATABASES = {
    "default": { 
        # Ends with "postgresql_psycopg2", "mysql", "sqlite3" or "oracle".
        "ENGINE": "django.db.backends.mysql",
        # DB name or path to database file if using sqlite3.
        "NAME": "djangotest",
        # Not used with sqlite3.
        "USER": "root",
        # Not used with sqlite3.
        "PASSWORD": "root",
        # Set to empty string for localhost. Not used with sqlite3.
        "HOST": "",
        # Set to empty string for default. Not used with sqlite3.
        "PORT": "",
    },
    "back": { 
        # Ends with "postgresql_psycopg2", "mysql", "sqlite3" or "oracle".
        "ENGINE": "django.db.backends.mysql",
        # DB name or path to database file if using sqlite3.
        "NAME": "djangotest2",
        # Not used with sqlite3.
        "USER": "root",
        # Not used with sqlite3.
        "PASSWORD": "root",
        # Set to empty string for localhost. Not used with sqlite3.
        "HOST": "localhost",
        # Set to empty string for default. Not used with sqlite3.
        "PORT": "",
    }
}
SYNCHRO_REMOTE = 'back'
SYNCHRO_DEBUG = True
So,when I open admin and add some objects,all saved successfully.

Then, issue python manage.py synchronize, always says "No changes since last synchronization."

I see there are synchro related tables:

mysql> show tables;
+----------------------------+
| Tables_in_djangotest       |
+----------------------------+
| auth_group                 |
| auth_group_permissions     |
| auth_permission            |
| auth_user                  |
| auth_user_groups           |
| auth_user_user_permissions |
| dbsettings_setting         |
| django_admin_log           |
| django_content_type        |
| django_migrations          |
| django_session             |
| synchro_changelog          |
| synchro_deletekey          |
| synchro_reference          |
| wnitest_answer             |
| wnitest_question           |
| xadmin_bookmark            |
| xadmin_usersettings        |
| xadmin_userwidget          |
+----------------------------+
My setup:

django: 1.7

django-dbsettings : 0.8

Anything wrong with my configuration or synchro cannot be used to local two databases?

Thanks.

Wesley

**Comment by weslie** [comment]
Anyone in project to help have a look?

**Comment by zlorf** [comment]
I will, but I need some time.

**Comment by weslie** [comment]
Thanks. I was just afraid of not anyone more here maintaining this project :-)

**Comment by zlorf** [comment]
Two local databases shouldn't change anything.
Please check whether:
- `synchro_changelog` table contains some data after adding/editing objects and dates are correct;
- there is `last_check` in table `dbsettings_setting` and its value is a past date (older that dates in `synchro_changelog`

**Comment by weslie** [comment]
Hi zlorf, please see the updated part in my question, seems no field 'last_check' in table dbsettings_setting, I just install this guy from pip, anything wrong?

**Comment by zlorf** [comment]
Did you set `SYNCHRO_MODELS` as stated in documentation? Your settings from first post lack this configuration.

**Comment by zlorf** [comment]
Please reopen if problem persist with `SYNCHRO_MODELS` defined.
