### ISSUE TITLE
Is django-synchro support 1.11?

### ISSUE THREAD

**Issue by elcolie** [zlorf/django-synchro#12]
Is django-synchro support 1.11?
Hope this project is still active developing

**Comment by zlorf** [comment]
Hi,
I'll check Django 1.11 compatibility (and maybe update the code) in the following days.

**Comment by ppeczek** [comment]
In django 1.11:
```ImportError: No module named 'signals'```
:(

**Comment by zlorf** [comment]
Ok, now I really started investigating it. Will provide Django 1.7 - 1.11 compatibility soon.

**Comment by zlorf** [comment]
Cheers, I've just uploaded 0.7 release that is (or: should be) compatible with Django 1.11 (and 1.8-1.10 as well).
