### ISSUE TITLE
ValueError: cannot use none as a query value

### ISSUE THREAD

**Issue by coolirisPunk** [zlorf/django-synchro#6]
Hi there, has anyone used this app before? I need some help it isnt working for me. Thnx.
I still can not get quite right configure the app and i got this error.

Y use Python 2.7.2, django 1.5.

![dsc_0177](https://cloud.githubusercontent.com/assets/8146466/3731142/17dc97a6-16e5-11e4-8a01-417f583d9310.jpg)
![dsc_0178](https://cloud.githubusercontent.com/assets/8146466/3731162/5093760a-16e5-11e4-9f6a-29c9671c3b75.jpg)

**Comment by zlorf** [comment]
Closing as no feedback was provided.
Please reopen if problem persists.

**Comment by Higgins723** [comment]
# 

> [`_**f**_`](fd)
